# Generated by Django 5.1.3 on 2024-11-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='wards',
        ),
    ]
