# Generated by Django 5.1.3 on 2024-11-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0002_alter_patient_table_alter_ward_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ward_id',
            new_name='ward',
        ),
    ]
